CREATE DATABASE [User];

USE [User];

GO
CREATE TABLE Users
(
FirstName NVARCHAR(50) NOT NULL, 
LastName NVARCHAR(50) NOT NULL, 
ProfileName NVARCHAR(100) NOT NULL,
MailId NVARCHAR(50) NOT NULL PRIMARY KEY,
Gender BINARY(1) NOT NULL,
ProfileImageId GUID NOT NULL,
About NVARCHAR(300) NOT NULL,
[Location] NVARCHAR(100) NOT NULL,
Intro NVARCHAR(100) NOT NULL,
);